"""Checkpoint compatibility helpers shared by training and analysis entrypoints."""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from typing import Any, Mapping


def unwrap_model(model: Any) -> Any:
    """Return the real model under DDP and torch.compile wrappers.

    PyTorch DDP exposes the wrapped module as ``.module``. ``torch.compile``
    exposes the original eager module as ``._orig_mod``. Saving and analysis
    should operate on the unwrapped module so downstream consumers do not see
    wrapper-specific key prefixes.
    """

    current = model
    seen: set[int] = set()
    while current is not None and id(current) not in seen:
        seen.add(id(current))
        module = getattr(current, 'module', None)
        if module is not None and module is not current:
            current = module
            continue
        orig = getattr(current, '_orig_mod', None)
        if orig is not None and orig is not current:
            current = orig
            continue
        return current
    return model


def load_torch_checkpoint(path: Path | str, *, map_location: Any = 'cpu') -> dict[str, Any]:
    """Load a project checkpoint with the explicit non-weights-only contract."""

    import torch

    checkpoint_path = Path(path)
    try:
        payload = torch.load(checkpoint_path, map_location=map_location, weights_only=False)
    except TypeError:  # torch<2.0 compatibility
        payload = torch.load(checkpoint_path, map_location=map_location)
    if not isinstance(payload, dict):
        raise ValueError(f'Checkpoint must load to a mapping: {checkpoint_path}')
    return payload


def checkpoint_state_dict(payload: Mapping[str, Any]) -> Mapping[str, Any]:
    """Return the model state dict from known project/checkpoint key variants."""

    for key in ('state_dict', 'model_state_dict', 'model_state', 'net_state_dict', 'network_state_dict', 'model', 'net', 'network'):
        value = payload.get(key)
        if isinstance(value, Mapping):
            return value
    # Some legacy tools saved the raw state_dict mapping itself. Treat a mapping
    # whose values are tensor-like/parameter-like as a state_dict rather than as
    # a metadata payload.
    if payload and all(hasattr(value, 'shape') or hasattr(value, 'detach') for value in payload.values()):
        return payload
    raise ValueError('Checkpoint is missing a model state_dict mapping.')


def normalize_state_dict_keys(state_dict: Mapping[str, Any]) -> OrderedDict[str, Any]:
    """Strip wrapper prefixes left by DDP/torch.compile on each key independently."""

    prefixes = ('module.', '_orig_mod.')
    normalized: OrderedDict[str, Any] = OrderedDict()
    for key, value in state_dict.items():
        text = str(key)
        changed = True
        while changed:
            changed = False
            for prefix in prefixes:
                if text.startswith(prefix):
                    text = text[len(prefix):]
                    changed = True
                    break
        normalized[text] = value
    return normalized


def _is_tolerated_missing_state_key(key: str) -> bool:
    # Pure-torch RF/LIF variants may register non-semantic threshold buffers
    # depending on trainable-threshold mode. Missing buffers are regenerated by
    # module construction and should not invalidate legacy checkpoints.
    return key.endswith('.v_threshold_buffer')


def _is_tolerated_unexpected_state_key(key: str) -> bool:
    # Older VGG adapter versions duplicated the first conv/LIF under aliases
    # in addition to ``core.features``. Those aliases do not represent separate
    # parameters in the current topology-only wrapper.
    if key.startswith('core.first_conv.') or key.startswith('core.first_lif.'):
        return True
    # SpikingJelly and eager runtime state may appear in legacy/ad-hoc payloads;
    # those are runtime states, not learned weights required for analysis.
    if '.v_float_to_tensor' in key or key.endswith('.v'):
        return True
    return False


def load_state_dict_compatible(
    model: Any,
    state_dict: Mapping[str, Any],
    *,
    context: str = 'Checkpoint state_dict',
    strict: bool = True,
) -> tuple[list[str], list[str], list[str], list[str]]:
    """Load ``state_dict`` after wrapper-prefix normalization.

    The loader remains strict for real parameter/shape mismatches, but tolerates
    known wrapper/runtime metadata differences caused by DDP, torch.compile,
    legacy VGG first-layer aliases, and pure-torch RF/LIF buffer policy.
    """

    normalized = normalize_state_dict_keys(state_dict)
    missing, unexpected = model.load_state_dict(normalized, strict=False)
    missing = list(missing)
    unexpected = list(unexpected)
    bad_missing = [key for key in missing if not _is_tolerated_missing_state_key(str(key))]
    bad_unexpected = [key for key in unexpected if not _is_tolerated_unexpected_state_key(str(key))]
    if strict and (bad_missing or bad_unexpected):
        raise RuntimeError(f'{context} mismatch: missing={bad_missing}, unexpected={bad_unexpected}')
    return missing, unexpected, bad_missing, bad_unexpected


def require_mapping(value: Any, *, name: str) -> Mapping[str, Any]:
    """Validate that ``value`` is a mapping and return it."""

    if not isinstance(value, Mapping):
        raise ValueError(f'{name} must be a mapping.')
    return value
