dataset_psd:
  dataset:
  - s-mnist
  - shd
  prep_root: /home/yongokhan/workspace/data/prep_data
  output_root: /home/yongokhan/workspace/result/neuron_motivation_scenario/dataset_psd/input_hann
  batch_size: 256
  num_workers: 2
  seed: 0
  gpu_index: 0
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  signal_curve_space: exact
  signal_curve_scale: raw
