element_fft:
  dataset: shd
  prep_root: /home/yongokhan/workspace/data/prep_data
  checkpoint: /home/yongokhan/workspace/result/ddp_train_scenario/03_dh_drf/shd_d_rf_4/checkpoints
  output_root: /home/yongokhan/workspace/result/element_fft_scenario/03_dh_drf/shd_d_rf_4
  num_workers: 2
  seed: 0
  gpu_index: 0
  anal_batch: 256
  low_vram: 0
