plotting:
  input_output:
    input: /home/yongokhan/workspace/result/rf_scinario/analysis/dvs_gesture_flatten/rf__filter_train__vth_fixed__reset_none/fft2d_analysis
    output: /home/yongokhan/workspace/result/rf_scinario/analysis/dvs_gesture_flatten/rf__filter_train__vth_fixed__reset_none/fft2d_analysis/plots
    output_root: ''
    manifest_name: recursive_plot_manifest.yaml
  rendering:
    format: png
    overwrite: true
    include_filter_count: false
  output:
    run_timestamp: ''
    timestamped_output: false
