dataset_fft:
  dataset:
  - s-mnist
  prep_root: /home/yongokhan/workspace/data/prep_data
  output_root: /home/yongokhan/workspace/result/dataset_fft_scenario/02_soft_fixed_clip/s-mnist_rf_soft_fixed_clip
  batch_size: 256
  num_workers: 2
  seed: 0
  gpu_index: 0
