dataset_psd:
  dataset:
  - s-mnist
  - shd
  prep_root: /home/yongokhan/workspace/data/prep_data
  output_root: /home/yongokhan/workspace/result/base/dataset_psd
  batch_size: 128
  num_workers: 0
  seed: 0
  gpu_index: 1
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: none
  signal_curve_space: exact
  signal_curve_scale: raw
