psd_analysis:
  checkpoint: /home/yongokhan/workspace/result/neuron_characterization_scenarios/regularization/exact_raw_noncentered_nondb_mean/simple/shd_lif_soft_fixed_l1_m0p001_l2_0p0/checkpoints
  dataset: shd
  prep_root: /home/yongokhan/workspace/data/prep_data
  output_root: /home/yongokhan/workspace/result/neuron_characterization_scenarios/regularization/exact_raw_noncentered_nondb_mean/simple/shd_lif_soft_fixed_l1_m0p001_l2_0p0/psd_analysis
  anal_batch: 128
  gpu_index: 0
  seed: 0
  num_workers: 2
  signal_curve_space: exact
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer:
  - mean
  signal_window: hann
  analysis_distance_metric:
  - centered_l2
  psd_curve_tokens:
  - exact_mean_raw_raw
  enable_pairwise_dependency_appendix: false
  enable_pca_1d: false
  enable_pca_mimo: false
  pca_ref_epoch: null
  pca_min_train_accuracy: 0.0
  pca_dim_per_layer: []
  low_vram: 0
  parameter_alpha_bin_edges: null
  parameter_alpha_bin_count: 10
  parameter_center_frequency_bin_edges: null
  parameter_center_frequency_bin_count: 10
  parameter_damping_bin_edges: null
  parameter_damping_bin_count: 10
  parameter_threshold_bin_edges: null
  parameter_threshold_bin_count: 10
