signal_curve_userbin_edges: null
signal_curve_userbin_reducer: mean
cases:
- dataset: s-mnist
  neuron_type: lif
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 1
  case: 00_window_lif_hann
  psd_analysis_config: psd_analysis/00_window_lif_hann.yaml
  regularized: false
  train_config: train/00_window_lif_hann.yaml
- dataset: s-mnist
  neuron_type: lif
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: none
  pca_dim_per_layer:
  - 1
  case: 00_window_lif_nowindow
  psd_analysis_config: psd_analysis/00_window_lif_nowindow.yaml
  regularized: false
  train_config: train/00_window_lif_nowindow.yaml
- dataset: s-mnist
  neuron_type: lif
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 4
  case: 01_baseline_lif
  psd_analysis_config: psd_analysis/01_baseline_lif.yaml
  regularized: false
  train_config: train/01_baseline_lif.yaml
- dataset: s-mnist
  neuron_type: rf
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 4
  case: 01_baseline_rf
  psd_analysis_config: psd_analysis/01_baseline_rf.yaml
  regularized: false
  train_config: train/01_baseline_rf.yaml
- dataset: s-mnist
  neuron_type: lif
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 1
  case: 02_psd_regularized_lif_pca1
  psd_analysis_config: psd_analysis/02_psd_regularized_lif_pca1.yaml
  regularized: true
  train_config: train/02_psd_regularized_lif_pca1.yaml
- dataset: s-mnist
  neuron_type: rf
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 1
  case: 02_psd_regularized_rf_pca1
  psd_analysis_config: psd_analysis/02_psd_regularized_rf_pca1.yaml
  regularized: true
  train_config: train/02_psd_regularized_rf_pca1.yaml
- dataset: s-mnist
  neuron_type: lif
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 4
  case: 03_psd_regularized_lif_pca4
  psd_analysis_config: psd_analysis/03_psd_regularized_lif_pca4.yaml
  regularized: true
  train_config: train/03_psd_regularized_lif_pca4.yaml
- dataset: s-mnist
  neuron_type: rf
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 4
  case: 03_psd_regularized_rf_pca4
  psd_analysis_config: psd_analysis/03_psd_regularized_rf_pca4.yaml
  regularized: true
  train_config: train/03_psd_regularized_rf_pca4.yaml
- dataset: shd
  neuron_type: rf
  recurrent: false
  reset: soft
  v_th:
  - train
  - 1.0
  filter: train
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: none
  pca_dim_per_layer:
  - 4
  case: 04_shd_rf_pca4_nowindow
  psd_analysis_config: psd_analysis/04_shd_rf_pca4_nowindow.yaml
  regularized: true
  train_config: train/04_shd_rf_pca4_nowindow.yaml
- dataset: s-mnist
  neuron_type: d_rf
  recurrent: false
  v_th:
  - fixed
  - 1.0
  filter: train
  branch: 4
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 4
  case: 05_candidate_drf4_hann
  psd_analysis_config: psd_analysis/05_candidate_drf4_hann.yaml
  regularized: false
  train_config: train/05_candidate_drf4_hann.yaml
- dataset: shd
  neuron_type: d_rf
  recurrent: false
  v_th:
  - fixed
  - 1.0
  filter: train
  branch: 4
  signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  pca_dim_per_layer:
  - 4
  case: 06_candidate_drf4_shd_hann
  psd_analysis_config: psd_analysis/06_candidate_drf4_shd_hann.yaml
  regularized: false
  train_config: train/06_candidate_drf4_shd_hann.yaml
dataset_psd_configs:
- signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: hann
  config: dataset_psd/input_psd_hann.yaml
- signal_curve_userbin_edges: null
  signal_curve_userbin_reducer: mean
  signal_window: none
  config: dataset_psd/input_psd_none.yaml
scenario: neuron_motivation_scenario
