element_psd:
  dataset: s-mnist
  prep_root: /home/yongokhan/workspace/data/prep_data
  checkpoint: /home/yongokhan/workspace/result/ddp_train_scenario/02_soft_fixed_clip/s-mnist_rf_soft_fixed_clip/checkpoints
  output_root: /home/yongokhan/workspace/result/element_psd_scenario/02_soft_fixed_clip/s-mnist_rf_soft_fixed_clip
  num_workers: 2
  seed: 0
  gpu_index: 0
  signal_window: hann
  anal_batch: 256
  low_vram: 0
