dataset_fft:
  dataset:
  - shd
  prep_root: /home/yongokhan/workspace/data/prep_data
  output_root: /home/yongokhan/workspace/result/dataset_fft_scenario/04_exact_pca1_centered_db_reg/shd_lif_soft_train_lambda_m0p001
  batch_size: 256
  num_workers: 2
  seed: 0
  gpu_index: 0
