fft2d_analysis:
  dataset: s-mnist
  prep_root: /home/yongokhan/workspace/data/prep_data
  checkpoint: /home/yongokhan/workspace/result/ddp_train_scenario/03_dh_drf/s-mnist_d_rf_4/checkpoints
  output_root: /home/yongokhan/workspace/result/2dfft_scenario/03_dh_drf/s-mnist_d_rf_4
  num_workers: 2
  seed: 0
  gpu_index: 0
  anal_batch: 256
  low_vram: 0
